name: ci
on: [push, pull_request]

jobs:
  build_and_deploy:
    env:
        # latest non-preview version at the time of writing this CI script
        BASE_VERSION: 5.0.0.2012
        DEFAULT_REF_TO_NUGET_PUSH: refs/heads/5.0.0
        BUILD_CONFIGURATION: Release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download Nuget.exe
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: 5.4.0
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Restore 
      run: |
        nuget restore Xamarin.Forms.sln -ConfigFile DevopsNuget.config
    - name: Build
      run: |
        ./build.ps1 -Target provision
        ./build.ps1 -Target BuildForNuget -ScriptArgs "--BUILD_CONFIGURATION=${env:BUILD_CONFIGURATION}"
    - name: Package and upload
      run: |
        git clone https://github.com/nblockchain/fsx
        $version = `.\fsx\Tools\fsi.bat fsx\Tools\nugetPush.fsx --output-version $env:BASE_VERSION`
        
        # Replaces '$version$' in nuspec files with version and '$Configuration$' with Release
        # Powershell code copied from script https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/build/steps/build-nuget.yml
        Get-ChildItem './.nuspec/*.nuspec' -Recurse | Foreach-Object {
             (Get-Content $_) | Foreach-Object  {
                 $_ -replace '\$version\$', $version `
                    -replace '\$Configuration\$', $env:BUILD_CONFIGURATION `
             } | Set-Content $_
        }

        nuget pack './.nuspec/Xamarin.Forms.nuspec'
        nuget pack './.nuspec/Xamarin.Forms.Platform.GTK.nuspec'

        If ($Env:GITHUB_REF -eq $Env:DEFAULT_REF_TO_NUGET_PUSH) {
            If ('${{ secrets.NUGET_API_KEY }}' -ne '') {
                nuget push "DotNetForms.$version.nupkg" -ApiKey ${{secrets.NUGET_API_KEY}} -Source https://api.nuget.org/v3/index.json    
                nuget push "DotNetForms.Platform.GTK.$version.nupkg" -ApiKey ${{secrets.NUGET_API_KEY}} -Source https://api.nuget.org/v3/index.json
            }
        }
    - name: Upload packages as CI artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        path: 'DotNetForms*.nupkg'